name: Documentation

on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Build and deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: |
          cp $GITHUB_EVENT_PATH docs/actions-event.json
          docker run --env-file docs/docker-env.list -t -v $PWD:/mnt -w /mnt tkpapp/texlive-julia-minimal docs/docker-script.sh 1.2
